### PR TITLE
DM-10942: MatrixMap with all zeros cannot be simplified

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by kfindeisen — APPROVED** [review]
Very thorough. I wouldn't have thought that the map would be invertible, but I guess checking if the underlying matrix has an inverse is nontrivial.

**Comment by r-owen** [comment]
Good point. I'll omit the test for the inverse since the expected behavior is not, perhaps, as obvious as I had thought and it's outside the scope of this ticket.

**Comment by kfindeisen** [comment]
Well, if it passes as-is, then it serves as documentation of what the expected behavior is, no?

**Comment by kfindeisen** [comment]
hmm, the AST manual says the inverse behavior depends on the matrix. I think you're right, we shouldn't be requiring that the inverse be `x -> NaN`.

**Pull request merged**
