### PR TITLE
DM-32517-v23: Remove debug message

### PR DESCRIPTION
**Pull request by mwittgen**

### CODE REVIEW

**Comment by timj** [comment]
I imagine we have to cherry pick the change to reusable workflow from #61

**Comment by timj** [comment]
I think we could probably just sync up v23.0.x with v24 (3829377)

**Comment by mwittgen** [comment]
Also needs cherry-pick https://github.com/lsst/astshim/commit/545b398f03e7ae468f27a5686b2434415c73109c

**Comment by timj** [comment]
Are we really sure you don't want to move the v23.0.x branch to the v24.0.0 tag? You are ending up there with all the cherry-picks.

**Comment by mwittgen** [comment]
This would also add https://github.com/lsst/astshim/pull/60/commits/117c15032a0c9fd8f6436a5857e18dfb92ecbf1f

**Comment by mwittgen** [comment]
But using v24.0.0 is cleaner. Making this change.

**Comment by mwittgen** [comment]
On the other hand, updating `v23.0.x` to `v24.0.0` violates the back port workflow. 
I am thinking how to fix the changelog and indicate backported tickets.
The clean way would be to backport all the cherry-picked tickets.Overkill here
as the essential backport is DM-32517

**Comment by timj** [comment]
Moving the branch to v24 is effectively backporting things in a much cleaner way than making entirely new commits with cherry-picking. @ktlim maybe we need to explicitly allow moving the release branch like this if the package has so little activity that it is simply a fast forward.

**Comment by TallJimbo** [comment]
My $0.02 (which I've put into practice on recent backports, since I thought this was broader than just me): if it really is just a pure fast-forward, then move the branch tip to a new point on `main`.  Anything else should be a real merge with a real merge commit.  This is consistent with not permitting force-pushes.

**Comment by timj** [comment]
@TallJimbo exactly. If you can fast forward to where you want to be then I don't see a down side with fast forwarding.

**Comment by TallJimbo** [comment]
I think there's a small downside in that it might seem inconsistent to our usual "always add a merge commit, never fast-forward" rule, but I think the situation for backports is sufficiently different to merit that.

**Comment by timj** [comment]
There is a merge commit on the commit we fast forward to. We aren't making any branches. I don't understand what the issue is. It seems odd to me to create a new branch to cherry pick everything across and then end up with exactly what we would have had if we had moved the branch to the newer merge commit.

**Comment by TallJimbo** [comment]
I agree with you!  I'm just saying that if somebody read our policy on merge commits elsewhere it might not be obvious that this is an exception.

**Comment by ktlim** [comment]
The difference here is between branching at the point of release (candidacy) and adding commits from main to the branch vs. moving the branch from the point of release to a place further along.  The software won't care, as it will be the same text.  The only loss would be in terms of historical insight into the process of getting to that text.  Unfortunately, it's not possible to put comments on branches, but I would be OK with a comment in the message for the first tag on the branch explaining why the branch point was fast-forwarded.

**Comment by mwittgen** [comment]
Would this be acceptable.
Always branch `23.0.x` from the `23.0.0.rc1` aka `23` base weekly as before.
Checkout an existing tag to forward to, like `24.0.0`
Push this to the back port merge request branch like `DM-32517-v23`
Merge  `DM-32517-v23` to `23.0.x`
The git log on the `23.0.x` branch as the merge ticket as record
```
commit e416159b237d01feda849c17cb9d4f4f9c267c2b (HEAD -> v23.0.x, origin/v23.0.x)
Merge: 45278ab 3829377
Author: 
Date:   Tue Feb 28 13:31:09 2023 -0800

    Merge pull request #1 from mwittgen/tickets/DM-32517-v23
    
    DM-32517-v23: Fast forward to 24.0.0

commit 38293774b485472d332af08230a572e74843271f (tag: w.2023.06, tag: w.2023.05, tag: w.2023.04, tag: w.2023.03, tag: w.2023.02, tag: w.2023.01, tag: w.2022.53, tag: w.2022.52, tag: w.2022.51, tag: w.2022.50, tag: w.2022.49, tag: w.2022.48, tag: w.2022.47, tag: w.2022.46, tag: w.2022.45, tag: w.2022.44, tag: w.2022.43, tag: w.2022.42, tag: w.2022.41, tag: w.2022.40, tag: w.2022.39, tag: w.2022.38, tag: w.2022.37, tag: w.2022.36, tag: w.2022.35, tag: w.2022.34, tag: w.2022.32, tag: w.2022.31, tag: w.2022.30, tag: w.2022.29, tag: w.2022.28, tag: w.2022.27, tag: w.2022.26, tag: w.2022.25, tag: w.2022.24, tag: w.2022.23, tag: v25.0.0.rc3, tag: v25.0.0.rc2, tag: v25.0.0.rc1, tag: v24.0.0.rc4, tag: v24.0.0.rc3, tag: v24.0.0.rc2, tag: v24.0.0.rc1, tag: 24.0.0, origin/tickets/DM-32517-v23, tickets/DM-32517-v23)
Merge: b04e0da d1c9c78
Author:
Date:   Thu May 26 16:26:52 2022 -0700

    Merge pull request #61 from lsst/reusable_workflows
    
    switch to reusable workflows

```
This would allow tracking in the changelog. From the last commit contained in this merge commit the earliest tag can be deducted, e.g.  `24.0.0`
https://github.com/mwittgen/astshim/pull/1/commits/d1c9c78d49e6f8259ab474488fe0f6cb4c7e03c2
I don't see mixing methods. Like cherry-picking to a branch, then forward to a tag.
But forward and cherry-pick.

**Comment by ktlim** [comment]
So this is essentially a merge from main to the release branch?  That does not seem unreasonable.  But I wouldn't call it a "fast forward", as it isn't.

**Comment by mwittgen** [comment]
> So this is essentially a merge from main to the release branch? That does not seem unreasonable. But I wouldn't call it a "fast forward", as it isn't.

Yes. It's merging from main up to a certain tag.

**Comment by mwittgen** [comment]
I assume this can be merged as is to get 23.0.4 going?

**Review by ktlim — APPROVED** [review]

**Comment by ktlim** [comment]
Doing this as three cherry-picks (one which is ahead of other commits not cherry-picked) is fine.

**Pull request merged**
